version: '3'
services:
  android-emulator:
    image: budtmo/docker-android:emulator_11.0
    privileged: true
    environment:
      - DISPLAY=:1.0
      - EMULATOR_DEVICE="Nexus 5"
      - DEVICE="Nexus 5"
      - AVD_DPI=240
      - AVD_NAME=emulator
      - EMULATOR_VERSION=11.0
      - TURN_OFF_EMULATOR_AFTER_USE=false
    volumes:
      - ./android:/root/.android
      - ./avd:/root/android_avd
    devices:
      - /dev/kvm:/dev/kvm
      - /dev/snd:/dev/snd
    ports:
      - "5554:5554" # adb控制端口
      - "5555:5555" # adb连接端口
      - "6080:6080" # VNC访问端口（通过noVNC的web界面访问）
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
