version: '3.8'

services:
  pve:
    image: makedie/proxmox_ve:8.3.1-1
    container_name: pve
    hostname: pve-docker
    privileged: true
    restart: always
    ports:
      - "8006:8006"  # Proxmox Web UI
      - "22:22"      # SSH
      - "5900:5900"   # VNC
    devices:
      - "/dev/kvm:/dev/kvm"
      - "/dev/vfio:/dev/vfio"
    volumes:
      - "./data/vz:/var/lib/vz"
      - "./data/pve-cluster:/var/lib/pve-cluster"
    environment:
      - TZ=Asia/Shanghai
      - root_password=root
    extra_hosts:
      - "pve-docker:10.0.8.1"
