services:
  pve:
    image: makedie/proxmox_ve:8.2.4
    container_name: pve
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      - /vol1/1000/pve:/var/lib/vz
    extra_hosts:
      - "pve:127.0.0.1"
    hostname: pve
    stop_grace_period: 2m
    privileged: true
